[project]
name = "stock-model-factory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pykrx>=1.0.51",
    "setuptools>=80.9.0",
]
